name: Build and test

on:
  push:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Add 3.1 bug
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x         
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Debug --no-restore
    - name: Unit Test
      working-directory: ./Function.Test
      run: dotnet test --no-restore --verbosity normal
    - name: Integration Test
      working-directory: ./Function.IT
      run: dotnet test --no-restore --verbosity normal