name: Build and test

on:
  push:
    branches:
        - main
        - develop

env:
  AZURE_WEBAPP_NAME: ToxicPlantsFunction
  WORKING_DIRECTORY: Function
  OUTPUT: Dotnetpublishfolder
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

jobs:
  build-test-deploy:
    name: Build and test
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Add 3.1 bug
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Restore NuGet packages
        run: dotnet restore
      - name: Begin Sonar scan
        run: |
          dotnet tool install --global dotnet-sonarscanner
          dotnet sonarscanner begin /o:animundo /k:Animundo_ToxicPlants /d:sonar.login=${{ secrets.SONAR_TOKEN }} /d:sonar.host.url=https://sonarcloud.io
      - name: Build and test
        run: |
          dotnet build --configuration Release --no-restore
          dotnet test Function.Test/Function.Tests.csproj --no-build --no-restore --verbosity normal -p:CollectCoverage=true -p:CoverletOutputFormat=opencover
      - name: End Sonar scan
        run: dotnet sonarscanner end /d:sonar.login=${{ secrets.SONAR_TOKEN }}
      - name: Integration test
        run: dotnet test Function.IT/Function.IT.csproj --no-restore --no-build --verbosity normal
      - name: dotnet publish
        if: github.ref == 'refs/heads/main'
        run: dotnet publish --configuration Release --output '${{ env.OUTPUT }}'
      - name: Deploy to Azure WebApp
        if: github.ref == 'refs/heads/main' 
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.SCM_CREDENTIALS }}
          package: '${{ env.WORKING_DIRECTORY }}/${{ env.OUTPUT }}'

