name: Publish to Azure

on:
  workflow_run:
    workflows: ["Build and test"]
    branches: [main]
    types:
      - completed

env:
  AZURE_WEBAPP_NAME: ToxicPlantsFunction
  WORKING_DIRECTORY: Function
  OUTPUT: Dotnetpublishfolder

jobs:
  build-and-deploy:
    name: Publish to Azure
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ${{ env.WORKING_DIRECTORY }}

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Add 3.1 bug
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x         
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: dotnet publish
      run: dotnet publish --configuration Release --output '${{ env.OUTPUT }}'
    - name: Deploy to Azure WebApp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.SCM_CREDENTIALS }}
        package: '${{ env.WORKING_DIRECTORY }}/${{ env.OUTPUT }}'
